---
- name: Install required packages for apt repository
  ansible.builtin.package:
    name: "{{ docker_debian_required_packages }}"
    state: present
    update_cache: true

- name: Uninstall old/conflicting Docker packages
  ansible.builtin.apt:
    name: "{{ docker_debian_conflicting_packages }}"
    state: absent
    purge: true
    autoremove: true

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: https://repo.mecan.ir/repository/debian-docker/gpg
    dest: /tmp/docker.gpg
    mode: "0644"

- name: Import Docker GPG key
  ansible.builtin.shell: |
    gpg --dearmor < /tmp/docker.gpg > /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg]
      https://repo.mecan.ir/repository/debian-docker
      {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add users to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
  when: docker_users is defined and docker_users | length > 0

- name: Ensure /etc/docker directory exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: "0755"

- name: Configure Docker daemon.json with registry mirrors
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries": ["https://docker.arvancloud.ir"],
        "registry-mirrors": ["https://docker.arvancloud.ir"]
      }
    owner: root
    group: root
    mode: "0644"
  notify: Restart Docker
  become: true
