version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    # depends_on:
    # - keycloak
    env_file:
      - ../../.env
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      # - source: database_conf
      # target: /etc/nginx/conf.d/database.conf
      # - source: grafana_conf
      # target: /etc/nginx/conf.d/grafana.conf
      # - source: keycloak.conf
      # target: /etc/nginx/conf.d/keycloak.conf
    secrets:
      - ssl_cert
      - ssl_key
    ports:
      - "80:80" # nginx HTTP
      - "443:443" # nginx HTTPS
      - "3000:3000" # grafana HTTP
      - "5050:5050" # database HTTP
      - "5051:5051" # database HTTPS
      - "8080:8080" # keycloak HTTP
      - "8443:8443" # keycloak HTTPS
    networks:
      - etl-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # restart_policy:
      #   condition: on-failure
      # resources:
      #   limits:
      #     cpus: "0.25"
      #     memory: 256M
      #   reservations:
      #     cpus: "0.1"
      #     memory: 128M
    volumes:
      - ./dockerize.ir:/etc/letsencrypt/live/dockerize.ir:ro
      - ./certbot/www:/var/www/certbot:ro

  # Certificate renewal service
  certbot:
    image: certbot/certbot:latest
    secrets:
      - ssl_cert
      - ssl_key
    depends_on:
      - nginx
    volumes:
      - ./dockerize.ir:/etc/letsencrypt/live/dockerize.ir:rw
      - ./certbot/www:/var/www/certbot:rw
    environment:
      - DOMAIN=dockerize.ir
      - EMAIL=your-email@example.com # Replace with your email
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet && kill -HUP $$(pidof nginx); sleep 12h & wait $${!}; done;'"
    networks:
      - etl-network
    deploy:
      placement:
        constraints:
          - node.role == manager
networks:
  etl-network:
    external: true

volumes:
  database_data:
    external: true
  replica_data:
    external: true
  pgadmin_data:
    external: true

configs:
  nginx_conf:
    file: ./nginx.conf
  # database_conf:
  #   file: ./conf.d/database.conf
  # grafana_conf:
  #   file: ./conf.d/grafana.conf
  # keycloak.conf:
  #   file: ./conf.d/keycloak.conf

secrets:
  ssl_cert:
    file: ../../secrets/fullchain.pem
  ssl_key:
    file: ../../secrets/privkey.pem
