services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - keycloak
    env_file:
      - ../../.env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      # For Let's Encrypt certificates
      - ../shared/certbot/conf:/etc/letsencrypt:ro
      - ../shared/certbot/www:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - etl-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M

  # Certificate renewal service
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ../shared/certbot/www:/var/www/certbot:rw
      - ../shared/certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - etl-network
    deploy:
      placement:
        constraints:
          - node.role == worker
