auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

storage_config:
  boltdb:
    directory: /loki/index
  filesystem:
    directory: /loki/chunks

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
  chunk_idle_period: 3m
  max_chunk_age: 1h

limits_config:
  max_query_length: 1h
  max_entries_limit: 5000
  retention_period: 168h # 7 days
