---
- name: Install NFS server package
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Create export directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
    owner: nobody
    group: nogroup
  with_items: "{{ nfs_exports }}"

- name: Configure exports
  template:
    src: exports.j2
    dest: /etc/exports
  notify: restart nfs

- name: Ensure NFS service is running
  systemd:
    name: nfs-kernel-server
    state: started
    enabled: yes

# Add entries to /etc/hosts if using hostnames
- name: Add NFS servers to hosts file
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    state: present
  loop:
    - master-1
    - master-2
    - worker1
