services:
  registry:
    image: registry:2
    env_file:
      - ../../.env
    secrets:
      - source: ssl_cert
        target: /etc/ssl/certs/fullchain.pem
      - source: ssl_key
        target: /etc/ssl/private/privkey.pem
      - source: registry-auth
        target: /etc/registry/auth/admin
    ports:
      - "5000:5000"
    networks:
      - etl_network
    volumes:
      - registry_data:/var/lib/registry
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}"
        labels: "service=registry"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  registry-ui:
    container_name: registery_ui
    image: joxit/docker-registry-ui:latest
    environment:
      - REGISTRY_TITLE="Dani Registry"
      - REGISTRY_URL=https://registry.dani-docker.ir
    depends_on:
      registry:
        condition: service_healthy
    networks:
      - etl_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

networks:
  etl_network:
    external: true

volumes:
  registry_data:
    driver: local
    name: registry_data

secrets:
  ssl_cert:
    file: ../../secrets/fullchain.pem
  ssl_key:
    file: ../../secrets/privkey.pem

  registry-auth:
    file: ../../services/registry/auth/admin
