services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - etl-network
    depends_on:
      - keycloak
      - nginx
    volumes:
      - frontend_data:/usr/share/nginx/html
    env_file:
      - .env
