version: "3.8"

services:
  database:
    image: postgres:15-alpine
    env_file:
      - ../../.env
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - etl-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 5s
      retries: 5

  backup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${POSTGRES_DB:-etl_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./backups:/backups
    depends_on:
      - database
    networks:
      - etl-network

  replica:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-etl_db}
      POSTGRES_USER: ${POSTGRES_USER:-replica}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-replica_pass}
    volumes:
      - replica_data:/var/lib/postgresql/data
      - ./replica-init:/docker-entrypoint-initdb.d
    networks:
      - etl-network
    depends_on:
      - database

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    command: etcd -name etcd0 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379
    ports:
      - "2379:2379"
    networks:
      - etl-network

  patroni:
    image: zalando/patroni:latest
    environment:
      PATRONI_SCOPE: etl-cluster
      PATRONI_NAME: node1
      PATRONI_RESTAPI_LISTEN: 0.0.0.0:8008
      PATRONI_ETCD_HOSTS: etcd:2379
      PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data
      PATRONI_POSTGRESQL_PASSWORD: postgres
      PATRONI_POSTGRESQL_SUPERUSER_PASSWORD: postgres
      PATRONI_POSTGRESQL_REPLICATION_PASSWORD: rep_pass
    volumes:
      - patroni_data:/var/lib/postgresql/data
    networks:
      - etl-network
    depends_on:
      - etcd

networks:
  etl-network:
    driver: bridge

volumes:
  database_data:
    name: database_data
  replica_data:
    name: replica_data
  patroni_data:
    name: patroni_data
