services:
  centraldb:
    image: postgres:15-alpine
    env_file:
      - ../../.env
    volumes:
      - centraldb_data:/var/lib/postgresql/data
      # Optionally mount custom init scripts:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - etl-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.storage == high
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
