services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    command:
      - start
      - --import-realm
    depends_on:
      - database
    env_file:
      - ../../.env
    environment:
      # JVM settings
      JAVA_OPTS_APPEND: >-
        -Xms1g -Xmx2g
        -XX:MetaspaceSize=96m
        -XX:MaxMetaspaceSize=256m
        -XX:+ParallelRefProcEnabled
        -XX:+UseStringDeduplication
        -Djava.net.preferIPv4Stack=true
    volumes:
      - keycloak_themes:/opt/keycloak/themes
      - ./realm-config:/opt/keycloak/data/import
      - ../../secrets/:/run/secrets:ro
    ports:
      - "8443:8443" # HTTPS port
      - "8080:8080" # HTTP port (behind reverse proxy)
    networks:
      - etl-network
