global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "codestar@gmail.com"
  smtp_authentication: "login"
  smtp_auth_username: "danialmobinidh81@gmail.com"
  smtp_auth_password: "qjxc spiu pqph vuwm"
  smtp_require_tls: true

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "email-notifications"
  routes:
    - match:
        severity: critical
      receiver: "email-notifications"
      group_wait: 10s

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "danialmobinidh81@gmail.com"
        send_resolved: true
        headers:
          subject: '{{ template "email.default.subject" . }}'
        html: '{{ template "email.default.html" . }}'

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "instance"]
