global:
  resolve_timeout: 5m
  smtp_smarthost: "${SMTP_SMARTHOST}"
  smtp_from: "${SMTP_FROM}"
  smtp_authentication: "${SMTP_AUTHENTICATION}"
  smtp_auth_username: "${SMTP_AUTH_USERNAME}"
  smtp_auth_password: "${SMTP_AUTH_PASSWORD}"
  smtp_require_tls: true

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "email-notifications"
  routes:
    - match:
        severity: critical
      receiver: "email-notifications"
      group_wait: 10s

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "${ALERT_RECIPIENT_EMAIL}"
        send_resolved: true
        headers:
          subject: '{{ template "email.default.subject" . }}'
        html: '{{ template "email.default.html" . }}'

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "instance"]
