# -----------------------------------------------
# Networks
# -----------------------------------------------
networks:
  etl-network:
    driver: overlay
    attachable: true
    name: etl-network

  monitoring-network:
    driver: overlay
    attachable: true
    name: monitoring-network

# -----------------------------------------------
# Volumes
# -----------------------------------------------
volumes:
  centraldb_data:
    driver: local
    name: centraldb_data

  frontend_data:
    driver: local
    name: frontend_data

  keycloak_themes:
    driver: local
    name: keycloak_themes

  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  alertmanager-data:
    driver: local
  loki-data:
    driver: local
    name: loki_data

  spark-data:
    driver: local
    name: spark_data
  spark-worker-data:
    driver: local
    name: spark_worker_data

# -----------------------------------------------
# Secrets
# -----------------------------------------------
secrets:
  ssl_cert:
    file: ../shared/fullchain.pem
  ssl_key:
    file: ../shared/privkey.pem

