version: "3.8"

services:
  # -----------------------------------------------
  # Backend
  # -----------------------------------------------

  # -----------------------------------------------
  # Database
  # -----------------------------------------------
  pg-0:
    image: bitnami/postgresql-repmgr:15
    env_file:
      - .env
    environment:
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    configs:
      - source: init_script
        target: /docker-entrypoint-initdb.d/01-init.sql
    volumes:
      - database_data:/bitnami/postgresql
    networks:
      - etl-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # resources:
      #   limits:
      #     cpus: "1"
      #     memory: 1G
      #   reservations:
      #     cpus: "0.5"
      #     memory: 512M

  pg-1:
    image: bitnami/postgresql-repmgr:15
    env_file:
      - .env
    environment:
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    configs:
      - source: replica_init_script
        target: /docker-entrypoint-initdb.d/01-pg-1-init.sql
    volumes:
      - replica_data:/bitnami/postgresql
    networks:
      - etl-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # resources:
      #   limits:
      #     cpus: "1"
      #     memory: 1G
      #   reservations:
      #     cpus: "0.5"
      #     memory: 512M

  database:
    image: haproxy:alpine
    configs:
      - source: ha-config
        target: /usr/local/etc/haproxy/haproxy.cfg
    networks:
      - etl-network
    # ports:
    # - "5432:5432"
    depends_on:
      - pg-0
      - pg-1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  backup:
    image: prodrigestivill/postgres-backup-local:17-alpine
    env_file:
      - .env
    # volumes:
    # - ./backups:/backups
    networks:
      - etl-network
    depends_on:
      - database
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # resources:
      #   limits:
      #     cpus: "0.5"
      #     memory: 512M
      #   reservations:
      #     cpus: "0.25"
      #     memory: 256M

  # -----------------------------------------------
  # Frontend
  # -----------------------------------------------

  # -----------------------------------------------
  # Keycloak
  # -----------------------------------------------
  keycloak:
    image: keycloak/keycloak:26.1
    command:
      - start
      - --import-realm
      - --proxy-headers=xforwarded
    depends_on:
      - database
    env_file:
      - .env
    environment:
      # JVM settings
      JAVA_OPTS_APPEND: >-
        -Xms1g -Xmx2g
        -XX:MetaspaceSize=96m
        -XX:MaxMetaspaceSize=256m
        -XX:+ParallelRefProcEnabled
        -XX:+UseStringDeduplication
        -Djava.net.preferIPv4Stack=true
    volumes:
      - keycloak_themes:/opt/keycloak/themes
    configs:
      - source: team1_realm
        target: /opt/keycloak/data/import/team1_realm.json
      - source: team2_realm
        target: /opt/keycloak/data/import/team2_realm.json
      - source: team3_realm
        target: /opt/keycloak/data/import/team3_realm.json
    secrets:
      - ssl_cert
      - ssl_key
    # ports:
    # - "8080:8080"
    # - "8443:8443"
    networks:
      - etl-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 1G

  # -----------------------------------------------
  # Monitoring
  # -----------------------------------------------
  node-exporter:
    image: prom/node-exporter:v1.6.0
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    # ports:
    # - "9100:9100"
    networks:
      - etl-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      # resources:
      #   limits:
      #     memory: 128M
      #   reservations:
      #     memory: 64M

  cadvisor:
    image: bitnami/cadvisor:0.53.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    privileged: true
    # TODO #23 find a way to use cadvisor without root
    user: root
    userns_mode: host
    # ports:
    # - "8080:8080"
    networks:
      - etl-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      # resources:
      #   limits:
      #     memory: 256M
      #   reservations:
      #     memory: 128M

  otel-collector:
    image: otel/opentelemetry-collector:0.132.0
    command: ["--config=/etc/otelcol/config.yaml"]
    configs:
      - source: otel_collector_config
        target: /etc/otelcol/config.yaml
    networks:
      - etl-network
    ports:
      - "8889:8889" # Prometheus exporter endpoint
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "13133:13133" # Health check endpoint
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # resources:
      #   limits:
      #     cpus: "0.5"
      #     memory: 512M
      #   reservations:
      #     cpus: "0.25"
      #     memory: 256M

  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus-data:/prometheus
    networks:
      - etl-network
    # ports:
    # - "9090:9090"
    depends_on:
      - otel-collector
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # resources:
      #   limits:
      #     cpus: "1"
      #     memory: 1G
      #   reservations:
      #     cpus: "0.5"
      #     memory: 512M

  loki:
    image: grafana/loki:3.1.0
    command: -config.file=/etc/loki/local-config.yaml
    configs:
      - source: loki_config
        target: /etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    networks:
      - etl-network
    # ports:
    # - "3100:3100"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # resources:
      #   limits:
      #     cpus: "0.5"
      #     memory: 512M
      #   reservations:
      #     cpus: "0.25"
      #     memory: 256M

  promtail:
    image: grafana/promtail:2.9.3
    command: -config.file=/etc/promtail/promtail-config.yaml
    configs:
      - source: promtail_config
        target: /etc/promtail/promtail-config.yaml
    volumes:
      - /var/log:/var/log:ro
    networks:
      - etl-network
    # ports:
    # - "9080:9080" # Promtail ready endpoint (optional, for health checks)
    depends_on:
      - loki
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # resources:
      #   limits:
      #     cpus: "0.25"
      #     memory: 256M
      #   reservations:
      #     cpus: "0.1"
      #     memory: 128M

  grafana:
    image: grafana/grafana:11.5
    # configs:
    # - source: grafana_provisioning_1
    # target: /etc/grafana/provisioning/file
    # - source: grafana_dashboards_1
    # target: /var/lib/grafana/dashboards/file.json
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - etl-network
    # ports:
    # - "3000:3000"
    depends_on:
      - prometheus
      - loki
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-q",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # resources:
      #   limits:
      #     cpus: "0.5"
      #     memory: 512M
      #   reservations:
      #     cpus: "0.25"
      #     memory: 256M

  alertmanager:
    image: prom/alertmanager:v0.26.0
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    # configs:
    # - source: alertmanager_config
    # target: /etc/alertmanager/alertmanager.yml
    networks:
      - etl-network
    # ports:
    # - "9093:9093"
    depends_on:
      - prometheus
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-q",
          "--tries=1",
          "--spider",
          "http://localhost:9093/-/healthy",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # resources:
      #   limits:
      #     cpus: "0.25"
      #     memory: 256M
      #   reservations:
      #     cpus: "0.1"
      #     memory: 128M

  # -----------------------------------------------
  # Nginx
  # -----------------------------------------------
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - keycloak
    env_file:
      - .env
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: database_conf
        target: /etc/nginx/conf.d/database.conf
      - source: grafana_conf
        target: /etc/nginx/conf.d/grafana.conf
      - source: keycloak.conf
        target: /etc/nginx/conf.d/keycloak.conf
    secrets:
      - ssl_cert
      - ssl_key
    ports:
      - "80:80" # nginx
      - "443:443" # nginx
      - "3000:3000" # grafana
      - "5432:5432" # database
      - "8080:8080" # keycloak
      - "8443:8443" # keycloak
    networks:
      - etl-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # restart_policy:
      #   condition: on-failure
      # resources:
      #   limits:
      #     cpus: "0.25"
      #     memory: 256M
      #   reservations:
      #     cpus: "0.1"
      #     memory: 128M

  # -----------------------------------------------
  # Spark
  # -----------------------------------------------
  spark-master:
    image: bitnami/spark:3.5.0
    env_file:
      - .env
    environment:
      - SPARK_MODE=master
    # ports:
    #   - "8080:8080" # Web UI
    #   - "7077:7077" # Spark master port
    configs:
      - source: spark-defaults
        target: /opt/bitnami/spark/conf/spark-defaults.conf
      - source: spark-metrics
        target: /opt/bitnami/spark/conf/metrics.properties
    volumes:
      - spark-data:/bitnami
      # TODO #21 find a way for binding ./data in docker swarm cluster
      # - ./data:/data
    networks:
      - etl-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # restart_policy:
      #   condition: on-failure
      # resources:
      #   limits:
      #     cpus: "1"
      #     memory: 1G
      #   reservations:
      #     cpus: "0.5"
      #     memory: 512M

  # Spark worker nodes
  spark-worker:
    image: bitnami/spark:3.5.0
    depends_on:
      - spark-master
    env_file:
      - .env
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    # ports:
    #   - "8081:8081" # Worker Web UI
    volumes:
      - spark-worker-data:/bitnami
      # TODO #21 find a way for binding ./data in docker swarm cluster
      # - ./data:/data
    networks:
      - etl-network
    deploy:
      mode: replicated
      replicas: 2 # Start with 2 workers, adjust based on your needs
      placement:
        constraints:
          - node.role == worker
        preferences:
          - spread: node.id
      # restart_policy:
      #   condition: on-failure
      # resources:
      #   limits:
      #     cpus: "1"
      #     memory: 1G
      #   reservations:
      #     cpus: "0.5"
      #     memory: 512M

  # Spark History Server for job history and logs
  spark-history-server:
    image: bitnami/spark:3.5.0
    command:
      - /opt/bitnami/spark/sbin/start-history-server.sh
    env_file:
      - .env
    environment:
      - SPARK_MODE=master # Using master mode for the history server
      - SPARK_HISTORY_FS_LOG_DIRECTORY=file:///spark-logs
    # ports:
    #   - "18080:18080" # History Server UI
    configs:
      - source: spark-defaults
        target: /opt/bitnami/spark/conf/spark-defaults.conf
    volumes:
      # TODO #21 find a way for binding ./data in docker swarm cluster
      - ~/spark-logs:/spark-logs
    networks:
      - etl-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # resources:
      #   limits:
      #     cpus: "0.25"
      #     memory: 256M
      #   reservations:
      #     cpus: "0.1"
      #     memory: 128M

# -----------------------------------------------
# Networks
# -----------------------------------------------
networks:
  etl-network:
    driver: overlay
    attachable: true
    name: etl-network

# -----------------------------------------------
# Volumes
# -----------------------------------------------
volumes:
  database_data:
    driver: local
    name: database_data
  replica_data:
    driver: local
    name: replica_data
  patroni_data:
    driver: local
    name: patroni_data

  frontend_data:
    driver: local
    name: frontend_data

  keycloak_themes:
    driver: local
    name: keycloak_themes

  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  loki-data:
    driver: local
    name: loki_data

  spark-data:
    driver: local
    name: spark_data
  spark-worker-data:
    driver: local
    name: spark_worker_data

# -----------------------------------------------
# Secrets
# -----------------------------------------------
secrets:
  ssl_cert:
    file: ./secrets/fullchain.pem
  ssl_key:
    file: ./secrets/privkey.pem
# -----------------------------------------------
# Configs
# -----------------------------------------------
configs:
  init_script:
    file: ./services/database/init/01-init.sql
  replica_init_script:
    file: ./services/database/replica-init/01-init.sql
  ha-config:
    file: ./services/database/haproxy.cfg

  etl_project_realm:
    file: ./services/keycloak/realm-config/etl-project-realm.json
  team1_realm:
    file: ./services/keycloak/realm-config/team1-realm.json
  team2_realm:
    file: ./services/keycloak/realm-config/team2-realm.json
  team3_realm:
    file: ./services/keycloak/realm-config/team3-realm.json

  otel_collector_config:
    file: ./services/monitoring/otel-collector/config.yaml
  prometheus_config:
    file: ./services/monitoring/prometheus/prometheus.yml
  promtail_config:
    file: ./services/monitoring/promtail/promtail-config.yaml
  loki_config:
    file: ./services/monitoring/loki/local-config.yaml
  # grafana_provisioning_1:
  # file: ./services/monitoring/grafana/provisioning/file
  # grafana_dashboards_1:
  # file: ./services/monitoring/grafana/dashboards/file.json
  # alertmanager_config:
  # file: ./services/monitoring/alertmanager/alertmanager.yml

  nginx_conf:
    file: ./services/nginx/nginx.conf
  database_conf:
    file: ./services/nginx/conf.d/database.conf
  grafana_conf:
    file: ./services/nginx/conf.d/grafana.conf
  keycloak.conf:
    file: ./services/nginx/conf.d/keycloak.conf

  spark-defaults:
    file: ./services/spark/conf/spark-defaults.conf
  spark-metrics:
    file: ./services/spark/conf/metrics.properties
