services:
  watchtower:
    image: containrrr/watchtower:1.7.1
    command: --interval 60 --cleanup
    env_file:
      - ../../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - etl_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
