global:
  scrape_interval: 15s # How often to scrape targets (default: 1m)
  evaluation_interval: 15s # How often to evaluate rules (default: 1m)
  scrape_timeout: 10s # Timeout for scraping targets

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "rules/alerts.yml"
  - "rules/recording.yml"