global:
  scrape_interval: 15s # How often to scrape targets (default: 1m)
  evaluation_interval: 15s # How often to evaluate rules (default: 1m)
  scrape_timeout: 10s # Timeout for scraping targets

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "/etc/prometheus/rules/*.yml"
