all:
  children:
    masters:
      hosts:
        master-1:
          remote_user: danial
        master-2:
          remote_user: danial
    workers:
      hosts:
        worker-1:
        worker-2:
        worker-3:
