---
- name: Prepare nodes for Docker Swarm
  hosts: all
  become: true
  roles:
    - role: user # Creates user, sets up SSH keys
      vars:
        user_name: "danial"
        user_groups: "sudo"
        user_pubkey_path: "roles/user/files/id_ed25519.pub"
        user_sudo: true
    - role: docker
      vars:
        docker_users: ["danial"]

- name: Configure NFS servers
  hosts: managers
  become: true
  roles:
    - role: nfs-server

- name: Configure NFS clients
  hosts: workers
  become: true
  roles:
    - role: nfs-client
